name: Publish Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    env:
      SOLUTION: 'src/GbxRemote.Net.sln'
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Dependencies
        run: dotnet restore $SOLUTION
      
      - name: Build Solution
        run: dotnet build $SOLUTION --configuration Release -p:Version=${{github.ref_name}} --no-restore
        
      - name: Run Tests
        run: dotnet test $SOLUTION /p:Configuration=Release --verbosity normal
      
      - name: Nuget Pack
        run: dotnet pack $SOLUTION /p:Version=${{github.ref_name}} -c Release --no-build --output package/
      
      - name: ZIP Artifacts
        uses: papeloto/action-zip@v1
        with:
            files: package/
            dest: package.zip
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ github.workspace }}/package.zip
      
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: atomicliquid # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
    
      # Push the package
      - name: NuGet push
        run: dotnet nuget push artifacts/my-sdk.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

